import { inject } from "@angular/core";
import { ForeignKey, TableColumn, TableDefinition } from "../../model/appdata";
import { ConstantValue } from "../../model/common";
import { BaseAuthService } from "../../service/auth.service";
import { SAIL_GUI_CONFIG, SailGuiConfig, DEFAULT_CONFIG } from "../../config";


export abstract class BaseTable {
    protected readonly cacheService = inject(BaseAuthService);
    protected readonly config: SailGuiConfig = inject(SAIL_GUI_CONFIG, {optional: true}) ?? DEFAULT_CONFIG;
    protected readonly dialogWidth: string = '400px';
    tableName = '';
    caption = '';
    fieldOptions: {[key: string]: ConstantValue[]} = {};
    fieldLabels: {[key: string]: string} = {};
    isReadOnlyBound = this.isReadOnly.bind(this);

    isReadOnly(_fieldName: string): boolean {
        return false;
    }

    titleCase(str: string): string {
        return str.replaceAll('_', ' ').toLowerCase().split(' ').map((word: string) => {
                return word.charAt(0).toUpperCase() + word.slice(1);
        }).join(' ');
    }

    getCaption() {
        if (!this.caption) {
            this.caption = this.titleCase(this.tableName);
        }
        return this.caption;
    }

    colCaption(fieldName: string): string {
        if (!this.fieldLabels[fieldName]) {
            const col = this.getColumn(fieldName);
            this.fieldLabels[fieldName] = col?.Caption || this.titleCase(fieldName);
        }
        return this.fieldLabels[fieldName];
    }

    canRead() {
        return this.cacheService.canRead(this.tableName);
    }

    canCreate() {
        return this.cacheService.canCreate(this.tableName);
    }

    canUpdate() {
        return this.cacheService.canUpdate(this.tableName);
    }

    canDelete() {
        return this.cacheService.canDelete(this.tableName);
    }

    emptyRecord(): any {
        const record : any = {[this.config.opField]: 'I'}
        const tableDef = this.cacheService.getTableDefinition(this.tableName);
        const tableOverride = this.config.tableOverrides?.[this.tableName];
        const editableTimestamps = new Set(tableOverride?.editableTimestamps ?? []);

        if (tableDef) {
            if (tableDef.Columns) {
                tableDef.Columns.forEach((field) => {
                    if (field.SequenceName) {
                        return; // auto-generated by database sequence
                    }
                    if (field.HasDefault && field.DataType === 'timestamp'
                        && !editableTimestamps.has(field.PascalName)) {
                        return; // audit column — server-managed, don't include
                    }
                    if (field.HasDefault && field.DataType !== 'timestamp') {
                        record[field.PascalName] = field.DataType === 'boolean'
                            ? field.DefaultValue === 'true'
                            : field.DefaultValue;
                    } else {
                        record[field.PascalName] = field.DataType === 'boolean' ? false : '';
                    }
                });
            }
            if (tableDef.Children) {
                tableDef.Children.forEach((child) => {
                    record[child.PascalName] = [];
                });
            }
            // Apply per-table default values from SailGuiConfig.tableOverrides (overrides DB defaults).
            // Values may be literals or zero-arg functions (evaluated now).
            const overrideDefaults = tableOverride?.defaultValues;
            if (overrideDefaults) {
                for (const [key, value] of Object.entries(overrideDefaults)) {
                    record[key] = typeof value === 'function' ? (value as () => unknown)() : value;
                }
            }
        }
        return record;
    }

    getDisplayedColumns(records: any[] = []): string[] {
        const tableDef = this.cacheService.getTableDefinition(this.tableName);
        const tableOverride = this.config.tableOverrides?.[this.tableName];
        const hidden = new Set([
            ...this.config.hiddenFields,
            ...(tableOverride?.hiddenFields ?? []),
        ]);
        const editableTimestamps = new Set(tableOverride?.editableTimestamps ?? []);
        if (tableDef && tableDef.Columns && tableDef.Columns.length > 0) {
            return tableDef.Columns
                .filter(col => !(col.HasDefault && col.DataType === 'timestamp'
                                 && !editableTimestamps.has(col.PascalName)))
                .sort((a, b) => a.Order - b.Order)
                .map((field) => field.PascalName)
                .filter(name => !hidden.has(name));
        } else if (records.length > 0) {
            return Object.keys(records[0]).filter(name => !hidden.has(name));
        }
        return [];
    }

    getColumn(fieldName: string): TableColumn | undefined {
        const tableDef = this.cacheService.getTableDefinition(this.tableName);
        if (tableDef && tableDef.Columns) {
            return tableDef.Columns.find((field) => field.PascalName === fieldName);
        }
        return undefined;
    }

    displayValue(fieldName: string, rawValue: any): string {
        if (rawValue === null || rawValue === undefined || rawValue === '') return '';
        const col = this.getColumn(fieldName);
        if (!col) return String(rawValue);
        if (col.LookupDomain) {
            const options = this.cacheService.getDomainValues(col.LookupDomain);
            const match = options?.find(o => o.Value === String(rawValue));
            if (match) return match.Caption ?? String(rawValue);
        }
        if (col.LookupTable && col.LookupStyle === 'D') {
            const options = this.cacheService.getTableValues(col.LookupTable);
            const match = options?.find(o => o.Value === String(rawValue));
            if (match) return match.Caption ?? String(rawValue);
        }
        return String(rawValue);
    }

    isTimeStamp(fieldName: string): boolean {
        const col = this.getColumn(fieldName)
        if (col) {
            return col.DataType === 'timestamp';
        }
        return fieldName.endsWith('Time') || fieldName.endsWith('time');
    }

    isNumber(fieldName: string): boolean {
        const col = this.getColumn(fieldName)
        if (col) {
            return col.DataType === 'integer' || col.DataType === 'float';
        }
        return false;
    }

    isBoolean(fieldName: string): boolean {
        const col = this.getColumn(fieldName)
        if (col) {
            return col.DataType === 'boolean' || col.LookupDomain === 'BOOLEAN';
        }
        return false;
    }

    isKey(fieldName: string): boolean {
        const col = this.getColumn(fieldName)
        if (col) {
            return (col.IsKey);
        }
        return false;
    }

    isArray(value: any): boolean {
        return Array.isArray(value);
    }

    formatTimeStamp(val: string): string {
        if (val && typeof val === 'string') {
            return val.slice(0, 16);
        }
        return val;
    }

    formatRecordTimeStamp(record: any) {
        if (record) {
            for (const key of Object.keys(record)) {
                if (this.isTimeStamp(key)) {
                    record[key] = this.formatTimeStamp(record[key]);
                }
            }
        }
    }

    restoreTimeStamp(val: any): any {
        // PostgreSQL can't cast '' to TIMESTAMP — normalize empty to null.
        if (val === '' || val === undefined || val === null) return null;
        if (typeof val === 'string' && !val.endsWith('Z')) {
            return val + ':00Z';
        }
        return val;
    }

    restoreRecordTimeStamp(record: any) {
        if (record) {
            for (const key of Object.keys(record)) {
                if (this.isTimeStamp(key)) {
                    record[key] = this.restoreTimeStamp(record[key]);
                }
            }
        }
    }

    readyToSave(record: any, original?: any) {
        this.restoreRecordTimeStamp(record);
        const op = record[this.config.opField];
        if (op === 'I' || op === 'D') return; // already marked
        // Original snapshot may carry display-formatted timestamps; restore both
        // sides to the same wire format before comparing, otherwise scalar
        // fields like Passdate look "modified" purely due to formatting.
        if (original) {
            const normalized = { ...original };
            this.restoreRecordTimeStamp(normalized);
            if (!this.isRecordDirty(record, normalized)) {
                record[this.config.opField] = 'R';
                return;
            }
        }
        record[this.config.opField] = 'U';
    }

    /** Shallow compare of own scalar fields, ignoring child arrays and op_code. */
    isRecordDirty(current: any, original: any): boolean {
        const opField = this.config.opField;
        for (const key of Object.keys(current)) {
            if (key === opField) continue;
            const curVal = current[key];
            // Ignore child-relation arrays; those have their own op_code per row.
            if (Array.isArray(curVal)) continue;
            if (curVal !== original[key]) return true;
        }
        return false;
    }

    getDialogData(record: any, isNew: boolean, readOnlyColumns: string[] = []): any {
        return {record, tableName: this.tableName, isNew, readOnlyColumns};
    }

    getTableName(fieldName: string): string {
        const tableDef = this.cacheService.getTableDefinition(this.tableName);
        if (!tableDef) return '';
        const fk = tableDef.Children?.find((c) => c.PascalName === fieldName);
        return fk ? fk.ChildTable : '';
    }

    getOptions(fieldName: string): ConstantValue[] | undefined {
        if (this.fieldOptions[fieldName]) {
            return this.fieldOptions[fieldName];
        }
        const col = this.getColumn(fieldName)
        if (col && col.LookupDomain) {
            return this.cacheService.getDomainValues(col.LookupDomain);
        }
        if (col && col.LookupTable && col.LookupStyle === 'D') {
            return this.cacheService.getTableValues(col.LookupTable);
        }
        return undefined;
    }

    getKeyFilters(record: any): {[key: string]: string} | undefined {
        const tableDef = this.cacheService.getTableDefinition(this.tableName);
        if (!tableDef || !tableDef.Keys || tableDef.Keys.length === 0) {
            return undefined;
        }
        const filters: {[key: string]: string} = {};
        for (const key of tableDef.Keys) {
            filters[key.PascalName] = record[key.PascalName];
        }
        return filters;
    }

    getForeignKeyConfig(parentTable: string): {fk: ForeignKey, parent: TableDefinition} | null{
        if (!parentTable) return null;
        const tableDef = this.cacheService.getTableDefinition(this.tableName);
        const parent = this.cacheService.getTableDefinition(parentTable);
        if (!tableDef || !tableDef.Keys || !tableDef.Parents || !parent) return null;
        const fk = tableDef.Parents.find((parent) => parent.ParentTable === parentTable);
        if (!fk) return null;
        return {'fk': fk, 'parent': parent};
    }

    initializeForeignKeys(record: any, parentTable: string, parentRecord: any) {
        const readOnlyColumns: string[] = [];
        const fkData = this.getForeignKeyConfig(parentTable);
        if (fkData && fkData.fk && fkData.parent) {
            fkData.fk.Columns.forEach((column, index) => {
                record[column.PascalName] = parentRecord[fkData.parent.Keys[index].PascalName];
                readOnlyColumns.push(column.PascalName);
            });
        }
    }

    buildSearchTerms(record: {[key: string]: any}): {[key: string]: string} {
        const hiddenSet = new Set(this.config.hiddenFields);
        const searchTerms: {[key: string]: string} = {};
        for (const key of Object.keys(record)) {
            if (hiddenSet.has(key)) continue;
            const val = record[key];
            if (val !== '' && val !== null && val !== undefined && !Array.isArray(val)) {
                searchTerms[key] = val;
            }
        }
        return searchTerms;
    }
}
